name: CI Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        name: Test on Python ${{ matrix.python-version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12"]

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry
                  poetry install

            - name: Run linting
              run: |
                  poetry run flake8 fastapifn/ --count --select=E9,F63,F7,F82 --show-source --statistics

            - name: Run type checking
              run: |
                  poetry run pyright

            - name: Run tests
              run: |
                  poetry run pytest tests -v -k 'not e2e'

            - name: Run tests with coverage
              run: |
                  poetry run pytest tests/ --cov=fastapifn --cov-report=xml --cov-report=term-missing -k 'not e2e'

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  file: ./coverage.xml
                  fail_ci_if_error: false
